version: "3.3"

services:
  master:
    image: mysql:latest
    container_name: master
    restart: always
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/config/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      TZ: Asia/Seoul
    ports:
      - "3307:3306"

  slave:
    image: mysql:latest
    container_name: slave
    restart: always
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/config/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    links:
      - master


networks:
  dock-net:
    driver: bridge