spring:
  datasource:
    write:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3308/cqrs?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: qwer1234

    read:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3308/cqrs?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: qwer1234

    hikari:
      auto-commit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
