spring:
  datasource:
    write:
      url: jdbc:mysql://localhost:3306/write?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234

    read:
      url: jdbc:mysql://localhost:3306/read?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: qwer1234

    hikari:
      auto-commit: false